version: "3.7"

services:
  flask:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    ports:
      - "5000:5000"
  celery:
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
  rabbitmq:
    image: rabbitmq:3.9.5

